accounts:
  message: "Welcome to abc accounts related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - "(453) 392-4829"
    - "(236) 203-0384"