spring:
  application:
    name: eurekaserver

server:
  port: 9999
  enable-self-preservation: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:9999/eureka/
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0



