spring:
  application:
    name: eurekaserver

server:
  port: 9999

eureka:
  client:
    register-with-eureka: false   # server does NOT register itself
    fetch-registry: false          # server does NOT fetch registry
    service-url:
      defaultZone: http://eureka-server:9999/eureka/  # used by clients

  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0

  instance:
    hostname: eurekaserver   # container name or DNS name in Docker network
